# Generated by Django 4.2.5 on 2023-10-04 12:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessoninfo',
            unique_together={('lesson', 'user')},
        ),
    ]
